services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: referral_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


  redis:
    image: redis:7
    networks:
      - app-network
    container_name: referral-redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"



    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: